name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  # Every Sunday at 4:20pm UTC
  schedule:
    - cron: '20 16 * * 0'

jobs:
  ci:
    name: CI
    # Only run cron on the dnadesign account
    if: (github.event_name == 'schedule' && github.repository_owner == 'dnadesign') || (github.event_name != 'schedule')
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
